import re

# Define the rule for detecting AI-generated comments

def evaluate(line):qq
    # Patterns to detect AI-generated comments
    ai_patterns = [
        re.compile(r'generated by AI', re.IGNORECASE),
        re.compile(r'created using AI', re.IGNORECASE),
        re.compile(r'using GPT-[\d.]+', re.IGNORECASE),
        re.compile(r'Copilot suggestion', re.IGNORECASE)
    ]

    ai_match_count = sum(bool(pattern.search(line)) for pattern in ai_patterns)

    # Calculate confidence score based on matches
    # Assuming each detected pattern increases the confidence by 25%
    confidence = min(100, ai_match_count * 25)

    return confidence